version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: police_data
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
    ports:
      - 5000:5000
